#include<iostream>
#include<ctime>
using namespace std;
int main()
{
    int computerNum, guess;
    int numGuesses = 0;

    //generate the random number between 1 to 100
    srand(time(0));
    //min + rand() % (max - min +1)
    computerNum = 1 + rand() % (100 - 1 +1);
    //cout << "The random number generated by the computer is " << computerNum << endl;
    //Explain the game to the user and get user's first guess
    cout << "I am thinking of a number between 1 to 100\n";
    cout << "Can you guess what it is? Enter your guess. " << endl;
    cin >> guess;
    numGuesses++;
    while(guess != computerNum)
    {
        if(guess > computerNum)
        {
            cout << "Your " << guess << " is too high, try a smaller number\n";
        }
        else
        {
            cout << "Your " << guess << " is too low, try a larger number\n";
        }
        cin >> guess;
        numGuesses++;
    }
    cout << "Congratulations. You got it , my number was " << computerNum << endl;
    cout << "It took you " << numGuesses << " guesses\n";
    system("pause");
    return 0;
}